export const sourcesData = [
    {
      id: 1,
      orderId: "W3Schools",
      url: "https://courses.w3schools.com/courses/javascript",
      name: "Illia Milevskiy",
      skills: ["HTML", "CSS", "Javascript","React", "WebPack", "FireBase", "Git"],
      type: "Beginner",
      email: "info@softnio.com",
      phone: "+811 847-4958",
      date: "23 Jan 2019, 10:45pm",
      invoiceItem1: "500.00",
      invoiceItem2: "500.00",
      invoiceItem3: "1000.00",
      invoiceItem4: "40.00",
      totalAmount: "95.00",
      status: "Recomended",
    },
    {
      id: 2,
      orderId: "Certified JavaScript Developer",
      url: "https://www.javascriptinstitute.org/javascript-certification/",
      name: "Ashley Lawson",
      skills: ["HTML", "CSS", "Javascript"],
      type: "Intermediate/Advanced",
      email: "ashley@softnio.com",
      phone: "+124 394-1787",
      date: "12 Jan 2020, 10:45pm",
      invoiceItem1: "50.00",
      invoiceItem2: "50.00",
      invoiceItem3: "10.00",
      invoiceItem4: "40.00",
      totalAmount: "70.00",
      status: "Not Recomended",
    },
    {
      id: 3,
      orderId: "Microsoft Technology Associate (MTA) Exam 98-382: Introduction to Programming Using JavaScript",
      url: "https://www.coursera.org/learn/html-css-javascript-for-web-developers",
      name: "Joe Larson",
      skills: ["HTML", "CSS", "Javascript", "Figma"],
      type: "Beginner",
      email: "larson@example.com",
      phone: "+168  603-2320",
      date: "26 Dec 2019, 12:15 pm",
      invoiceItem1: "50.00",
      invoiceItem2: "200.00",
      invoiceItem3: "200.00",
      invoiceItem4: "50.00",
      totalAmount: "127.00",
      status: "Recomended",
    },
    {
      id: 4,
      orderId: "CIW JavaScript Specialist",
      url: "https://www.ciwcertified.com/ciw-certifications/web-development-series/javascript-specialist",
      name: "Jane Montgomery",
      skills: ["HTML", "CSS", "Javascript", "Figma"],
      type: "Intermediate",
      email: "jane84@example.com",
      phone: "+439 271-5360",
      date: "21 Jan 2019, 6:12 am",
      invoiceItem1: "1500.00",
      invoiceItem2: "500.00",
      invoiceItem3: "1000.00",
      invoiceItem4: "600.00",
      totalAmount: "Free",
      status: "Not Recomended",
    },
    {
      id: 5,
      orderId: "Microsoft Certified Solutions Associate (MCSA: Web Applications) Exam 70-480: Programming in HTML5 with JavaScript and CSS3",
      url: "https://docs.microsoft.com/en-us/learn/certifications/exams/70-480",
      name: "Frances Burns",
      skills: ["Javascript"],
      type: "Intermediate",
      email: "frances@example.com",
      phone: "+639 130-3150",
      date: "21 Jan 2019, 6 :12 am",
      invoiceItem1: "100.00",
      invoiceItem2: "100.00",
      invoiceItem3: "50.00",
      invoiceItem4: "40.00",
      totalAmount: "165.00",
      status: "Not Recomended",
    },
  ];
  